
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


#For Worker Side
wregistermodel = model.WRegistrationModel
wloginmodel = model.WLoginModel
WRegister = /WEB-INF/JSP/WRegister.jsp
WLogin = /WEB-INF/JSP/WLogin.jsp
WHome = /WEB-INF/JSP/WHome.jsp
whomemodel = model.WHomeModel
WProfile = /WEB-INF/JSP/WProfile.jsp
wprofilemodel = model.WProfileModel
wnotificationmodel = model.WNotificationModel
WNotification = /WEB-INF/JSP/WNotification.jsp
wupdatinghirestatusmodel = model.WUpdatingHireStatusModel
wlogoutmodel = model.WLogoutModel
wupdateavailabilitymodel = model.WUpdateAvailabilityModel
WMyProfile = /WEB-INF/JSP/WMyProfile.jsp
wmyprofilemodel = model.WMyProfileModel



# for Employer Side
ERegister = /WEB-INF/JSP/ERegister.jsp
ELogin = /WEB-INF/JSP/ELogin.jsp
eregistermodel = model.ERegistrationModel
eloginmodel = model.ELoginModel
EHome = /WEB-INF/JSP/EHome.jsp
EListOfWorker =/WEB-INF/JSP/EListOfWorker.jsp
elistofworkermodel = model.EListOfWorkerModel
EWorkerProfile = /WEB-INF/JSP/EWorkerProfile.jsp
eworkerprofilemodel = model.EWorkerProfileModel
ehireworkermodel = model.EHireWorkerModel
EHireWorkerStatus = /WEB-INF/JSP/EHireWorkerStatus.jsp
ehireworkerstatusmodel = model.EHireWorkerStatusModel
elogoutmodel = model.ELogoutModel
EMyProfile = /WEB-INF/JSP/EMyProfile.jsp
ecancelrequestmodel = model.ECancelRequestModel
AdminAddNewAdmin = 


#For Admin Side
AdminLogin = /WEB-INF/JSP/AdminLogin.jsp
adminloginmodel = model.AdminLoginModel
AdminDashboard = /WEB-INF/JSP/AdminDashboard.jsp
admindashboardmodel = model.AdminDashboardModel
AdminTotalWorkerList = /WEB-INF/JSP/AdminTotalWorkerList.jsp
admintotaluserslistmodel = model.AdminTotalUsersListModel
adminupdatingstatusmodel = model.AdminUpdatingStatusModel
AdminTotalEmployerList = /WEB-INF/JSP/AdminTotalEmployerList.jsp
AdminTotalAdminsList = /WEB-INF/JSP/AdminTotalAdminsList.jsp
AdminTotalHireRequestsList = /WEB-INF/JSP/AdminTotalHireRequestsList.jsp
AdminTotalPendingRequestList = /WEB-INF/JSP/AdminTotalPendingRequestList.jsp
AdminTotalBannedUsersList = /WEB-INF/JSP/AdminTotalBannedUsersList.jsp
AdminAddNewAdmin = /WEB-INF/JSP/AdminAddNewAdmin.jsp
adminaddnewadminmodel = model.AdminAddNewAdminModel
adminviewdetailsmodel = model.AdminViewDetailsModel
adminlogoutmodel = model.AdminLogoutModel
AdminViewDetails = /WEB-INF/JSP/AdminViewDetails.jsp



#For Image getting
serveimagemodel = model.ServeImageModel

#For Logout



#//Note - 
